# Generated by Django 4.1 on 2022-08-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminconfigs',
            options={'verbose_name': 'Админ конфигурация', 'verbose_name_plural': 'Админ конфигурации'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AlterModelOptions(
            name='usersecuredata',
            options={'verbose_name': 'Данные о клиенте', 'verbose_name_plural': 'Данные о клиентах'},
        ),
        migrations.AlterModelOptions(
            name='usersemailverifytokens',
            options={'verbose_name': 'Верификация почты', 'verbose_name_plural': 'Верификация почты'},
        ),
        migrations.AlterModelOptions(
            name='userspaychecks',
            options={'verbose_name': 'Проверка оплат', 'verbose_name_plural': 'Проверка оплаты'},
        ),
        migrations.AlterModelOptions(
            name='usersprofile',
            options={'verbose_name': 'Профиль клиента', 'verbose_name_plural': 'Профиль клиентов'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='videos',
            name='video_data',
            field=models.FileField(blank=True, null=True, upload_to='service_videos/', verbose_name='Видео'),
        ),
    ]
