# Generated by Django 4.1 on 2022-09-03 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='user_service_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cryptency.services'),
        ),
    ]
