# Generated by Django 4.1 on 2022-08-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptency', '0002_alter_adminconfigs_options_alter_services_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_description',
            field=models.TextField(verbose_name='Описание сервиса'),
        ),
    ]
