# Generated by Django 4.1 on 2022-09-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptency', '0002_alter_usersprofile_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspaychecks',
            name='service_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название сервиса'),
        ),
    ]
