# Generated by Django 4.1 on 2022-08-31 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptency', '0003_alter_services_service_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersecuredata',
            name='user_city',
        ),
        migrations.RemoveField(
            model_name='usersecuredata',
            name='user_corpus',
        ),
        migrations.RemoveField(
            model_name='usersecuredata',
            name='user_country_of_operation',
        ),
        migrations.RemoveField(
            model_name='usersecuredata',
            name='user_country_of_operation_status',
        ),
        migrations.RemoveField(
            model_name='usersecuredata',
            name='user_country_subject',
        ),
        migrations.RemoveField(
            model_name='usersecuredata',
            name='user_home',
        ),
        migrations.RemoveField(
            model_name='usersecuredata',
            name='user_index',
        ),
        migrations.RemoveField(
            model_name='usersecuredata',
            name='user_middle_name',
        ),
        migrations.RemoveField(
            model_name='usersecuredata',
            name='user_room',
        ),
        migrations.RemoveField(
            model_name='usersecuredata',
            name='user_room_num',
        ),
        migrations.RemoveField(
            model_name='usersecuredata',
            name='user_street',
        ),
    ]
