# Generated by Django 4.1 on 2022-09-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptency', '0003_alter_usersprofile_user_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspaychecks',
            name='service_pk',
            field=models.IntegerField(verbose_name='ID сервиса'),
        ),
    ]
