# Generated by Django 4.1 on 2022-09-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptency', '0004_alter_userspaychecks_service_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='user_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
