# Generated by Django 4.1 on 2022-09-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptency', '0005_usersprofile_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='userswithdraw',
            name='user_withdraw_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата заявки'),
        ),
    ]
