# Generated by Django 4.1 on 2022-08-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptency', '0006_alter_adminconfigs_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspaychecks',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплатил?'),
        ),
    ]
