# Generated by Django 4.1 on 2022-08-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptency', '0008_services_service_simbole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='service_price',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_simbole',
        ),
        migrations.AddField(
            model_name='services',
            name='service_price1',
            field=models.CharField(default=50, max_length=100, verbose_name='Цена сервиса на USD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='service_price2',
            field=models.CharField(default=50, max_length=100, verbose_name='Цена сервиса на BYN'),
            preserve_default=False,
        ),
    ]
