# Generated by Django 4.1 on 2022-08-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptency', '0009_remove_services_service_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminconfigs',
            name='ref_bonus',
        ),
        migrations.AddField(
            model_name='adminconfigs',
            name='ref_bonus1',
            field=models.IntegerField(default=10, verbose_name='Реф.бонус 1 уровень'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminconfigs',
            name='ref_bonus2',
            field=models.IntegerField(default=10, verbose_name='Реф.бонус 2 уровень'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminconfigs',
            name='ref_bonus3',
            field=models.IntegerField(default=10, verbose_name='Реф.бонус 3 уровень'),
            preserve_default=False,
        ),
    ]
